# -*- coding: utf-8 -*-
"""Project_SupplyChian3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Fd5K7uebLprmUxPg5SEICcExl6u-NIl
"""

import pandas as pd

df = pd.read_csv("DataCoSupplyChain.csv", encoding='latin1')

print(df.shape)
print(df.head())
print(df.info())

df.isnull().sum()

df.describe()

df = df.drop(columns=['Product Description'])

df.head()

df = df.drop(columns=['Order Zipcode'])
df.head()

df.isnull().sum()

numeric_cols = df.select_dtypes(include=['float64', 'int64']).columns

for col in numeric_cols:
    df[col].fillna(df[col].median(), inplace=True)

categorical_cols = df.select_dtypes(include=['object']).columns

for col in categorical_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

df.head()

df.isnull().sum()

print("Duplicate Rows:", df.duplicated().sum())

print(df)

df['Product Status'].value_counts()
